runtime: nodejs10

services:
  - postgresql

before_script:
  - npm install
  - psql -c 'create database fintech28;' -U postgres

script:
  - npm run test
  env: standard

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
